# Site settings
title: 李炫毅 / Xuanyi Li
description: 李炫毅（Xuanyi Li），现任众擎机器人（EngineAI Robotics）具身模型负责人，负责数据闭环系统，并推进具身 Agent、VLA 与世界模型研发。此前任职于小鹏汽车、大疆车载。
favicon: /assets/img/myphoto.jpg
baseurl:
url: https://meteorshowers.github.io
rss_url:

# Build settings

highlight: true
#highlighter: rouge

timezone: Asia/Shanghai

markdown: kramdown
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style
